import express from 'express';
import cors from 'cors';

const app = express();
app.use(cors());
app.use(express.json());

// SLA_DATA for Node.js backend
const SLA_DATA = [
  { service: "Analysis Services", sla: 0.9990 },
  { service: "API Center Services - Standard Plan", sla: 0.9995 },
  { service: "API Management Services - Single Region", sla: 0.9995 },
  { service: "API Management Services Premium - Multi-region", sla: 0.9999 },
  { service: "App Configuration", sla: 0.9990 },
  { service: "App Service - Non-Zonal", sla: 0.9995 },
  { service: "App Service - Zone Redundant", sla: 0.9999 },
  { service: "Application Gateway", sla: 0.9995 },
  { service: "Application Gateway for Containers", sla: 0.9995 },
  { service: "Application Insights", sla: 0.999 },
  { service: "Automation", sla: 0.999 },
  { service: "Azure Active Directory B2C", sla: 0.9999 },
  { service: "Azure AI Search", sla: 0.999 },
  { service: "Azure API for FHIR", sla: 0.999 },
  { service: "Azure Applied AI Services", sla: 0.999 },
  { service: "Azure Arc", sla: 0.999 },
  { service: "Azure Backup", sla: 0.999 },
  { service: "Azure Bastion", sla: 0.9995 },
  { service: "Azure Bot Service", sla: 0.999 },
  { service: "Azure Cache for Redis - Multi-Region", sla: 0.99999 },
  { service: "Azure Cache for Redis - Non-Zonal", sla: 0.999 },
  { service: "Azure Cache for Redis - Zone Redundant", sla: 0.9999 },
  { service: "Azure Chaos Studio", sla: 0.999 },
  { service: "Azure Cognitive Services", sla: 0.999 },
  { service: "Azure Communication Gateway", sla: 0.9999 },
  { service: "Azure Communication Services", sla: 0.999 },
  { service: "Azure Confidential Ledger", sla: 0.999 },
  { service: "Azure Container Apps", sla: 0.9995 },
  { service: "Azure Container Instances", sla: 0.999 },
  { service: "Azure Container Registry", sla: 0.999 },
  { service: "Azure Data Explorer", sla: 0.999 },
  { service: "Azure Data Factory", sla: 0.999 },
  { service: "Azure Database for MariaDB", sla: 0.9999 },
  { service: "Azure Database for MySQL - Flexible Server - Non HA", sla: 0.999 },
  { service: "Azure Database for MySQL - Flexible Server - Same Zone HA", sla: 0.9995 },
  { service: "Azure Database for MySQL - Flexible Server - Zone Redundant", sla: 0.9999 },
  { service: "Azure Database for MySQL - Single Server", sla: 0.9999 },
  { service: "Azure Database for PostgreSQL - Flexible Server - Non HA", sla: 0.999 },
  { service: "Azure Database for PostgreSQL - Flexible Server - Same Zone HA", sla: 0.9995 },
  { service: "Azure Database for PostgreSQL - Flexible Server - Zone Redundant", sla: 0.9999 },
  { service: "Azure Database for PostgreSQL - Single Server", sla: 0.9999 },
  { service: "Azure Databricks", sla: 0.9995 },
  { service: "Azure DDoS Protection", sla: 0.9999 },
  { service: "Azure Defender", sla: 0.999 },
  { service: "Azure Dev Box", sla: 0.999 },
  { service: "Azure Dev Ops", sla: 0.999 },
  { service: "Azure Dev Ops Pipelines", sla: 0.999 },
  { service: "Azure Digital Twins", sla: 0.999 },
  { service: "Azure DNS", sla: 1 },
  { service: "Azure DNS Private Resolver", sla: 0.9999 },
  { service: "Azure ExpressRoute Circuit (2+ Sites)", sla: 0.9995 },
  { service: "Azure ExpressRoute Circuit (Metro)", sla: 0.999 },
  { service: "Azure ExpressRoute Circuit (Single Site)", sla: 0.99 },
  { service: "Azure ExpressRoute Traffic Collector", sla: 0.999 },
  { service: "Azure Files - Premium Tier", sla: 0.9999 },
  { service: "Azure Firewall - Single Zone", sla: 0.9995 },
  { service: "Azure Firewall - Zone Redundant", sla: 0.9999 },
  { service: "Azure Fluid Relay", sla: 0.999 },
  { service: "Azure Front Door", sla: 0.9999 },
  { service: "Azure Function App - Consumption Plan", sla: 0.9995 },
  { service: "Azure Function App - Dedicated App Service Plan", sla: 0.9995 },
  { service: "Azure Function App - Premium Plan", sla: 0.9995 },
  { service: "Azure Information Protection", sla: 0.999 },
  { service: "Azure IoT Central", sla: 0.999 },
  { service: "Azure IoT Hub", sla: 0.999 },
  { service: "Azure IoT Hub Device Provisioning Service", sla: 0.999 },
  { service: "Azure Key Vault", sla: 0.9999 },
  { service: "Azure Key Vault Managed HSM", sla: 0.999 },
  { service: "Azure Kubernetes Service (AKS) API Server - Regional", sla: 0.999 },
  { service: "Azure Kubernetes Service (AKS) API Server - Zone Redundant", sla: 0.9995 },
  { service: "Azure Lab Services", sla: 0.999 },
  { service: "Azure Load Balancer - Standard Tier", sla: 0.9999 },
  { service: "Azure Load Testing", sla: 0.999 },
  { service: "Azure Machine Learning - Compute Management", sla: 0.999 },
  { service: "Azure Machine Learning - Realtime Scoring", sla: 0.999 },
  { service: "Azure Managed Grafana", sla: 0.999 },
  { service: "Azure Managed Instance for Apache Cassandra - Compliant Networking / Multi Region / Zone Redundant", sla: 0.99999 },
  { service: "Azure Managed Instance for Apache Cassandra - Compliant Networking / Single Region / Non Zonal", sla: 0.9995 },
  { service: "Azure Managed Instance for Apache Cassandra - Compliant Networking / Single Region / Zone Redundant", sla: 0.9999 },
  { service: "Azure Managed Instance for Apache Cassandra - Single Region / Non Zonal", sla: 0.99995 },
  { service: "Azure Managed Instance for Apache Cassandra - Single Region / Zone Redundant", sla: 0.99995 },
  { service: "Azure Maps", sla: 0.999 },
  { service: "Azure Monitor Alerts", sla: 0.999 },
  { service: "Azure Monitor Managed Service for Prometheus", sla: 0.999 },
  { service: "Azure Monitor Notification Delivery ", sla: 0.999 },
  { service: "Azure NAT Gateway", sla: 0.9999 },
  { service: "Azure NetApp Files", sla: 0.9999 },
  { service: "Azure OpenAI Service", sla: 0.999 },
  { service: "Azure Operator Insights", sla: 0.999 },
  { service: "Azure Operator Service Manager", sla: 0.999 },
  { service: "Azure Orbital Ground Station", sla: 0.999 },
  { service: "Azure Private 5G Core - Edge Service", sla: 0.999 },
  { service: "Azure Private 5G Core - Online Service", sla: 0.999 },
  { service: "Azure Private Link", sla: 0.9999 },
  { service: "Azure Red Hat OpenShift", sla: 0.9995 },
  { service: "Azure Route Server", sla: 0.9995 },
  { service: "Azure SignalR Service", sla: 0.999 },
  { service: "Azure Site Recovery", sla: 0.999 },
  { service: "Azure Spatial Anchors", sla: 0.999 },
  { service: "Azure Spring Apps - Enterprise Tier", sla: 0.9995 },
  { service: "Azure Spring Apps - Standard Tier", sla: 0.999 },
  { service: "Azure SQL Database - Non Zonal", sla: 0.9999 },
  { service: "Azure SQL Database - Standard or Basic", sla: 0.9999 },
  { service: "Azure SQL Database - Zone Redundant", sla: 0.99995 },
  { service: "Azure SQL Managed Instance", sla: 0.9999 },
  { service: "Azure Stream Analytics", sla: 0.999 },
  { service: "Azure Synapse Analytics", sla: 0.999 },
  { service: "Azure Virtual Network Manager", sla: 0.999 },
  { service: "Azure Virtual WAN", sla: 0.9995 },
  { service: "Azure VMware Solution - Management Tools", sla: 0.999 },
  { service: "Azure VMware Solution - Workload Infrastructure", sla: 0.999 },
  { service: "Azure Web PubSub", sla: 0.999 },
  { service: "Batch", sla: 0.999 },
  { service: "Bing Maps Enterprise", sla: 0.999 },
  { service: "Bing Maps Mobile Asset Management", sla: 0.999 },
  { service: "BizTalk Services", sla: 0.999 },
  { service: "Cloud Services", sla: 0.9995 },
  { service: "Content Delivery Network", sla: 0.999 },
  { service: "Cosmos DB for Apache Cassandra - Multi-Region Read", sla: 0.99999 },
  { service: "Cosmos DB for Apache Cassandra - Multi-Region Write", sla: 0.99999 },
  { service: "Cosmos DB for Apache Cassandra - Single Region", sla: 0.9999 },
  { service: "Cosmos DB for Apache Cassandra - Zone Redundant", sla: 0.99995 },
  { service: "Cosmos DB for Apache Gremlin - Multi-Region Read", sla: 0.99999 },
  { service: "Cosmos DB for Apache Gremlin - Multi-Region Write", sla: 0.99999 },
  { service: "Cosmos DB for Apache Gremlin - Single Region", sla: 0.9999 },
  { service: "Cosmos DB for Apache Gremlin - Zone Redundant", sla: 0.99995 },
  { service: "Cosmos DB for MongoDB RU - Multi-Region Read", sla: 0.99999 },
  { service: "Cosmos DB for MongoDB RU - Multi-Region Write", sla: 0.99999 },
  { service: "Cosmos DB for MongoDB RU - Single Region", sla: 0.9999 },
  { service: "Cosmos DB for MongoDB RU - Zone Redundant", sla: 0.99995 },
  { service: "Cosmos DB for MongoDB vCore - Multi-Region", sla: 0.99995 },
  { service: "Cosmos DB for MongoDB vCore - Single-Region", sla: 0.9999 },
  { service: "Cosmos DB for NoSQL - Multi-Region Read", sla: 0.99999 },
  { service: "Cosmos DB for NoSQL - Multi-Region Write", sla: 0.99999 },
  { service: "Cosmos DB for NoSQL - Single Region", sla: 0.9999 },
  { service: "Cosmos DB for NoSQL - Zone Redundant", sla: 0.99995 },
  { service: "Cosmos DB for PostreSQL", sla: 0.9999 },
  { service: "Cosmos DB for Table - Multi-Region Read", sla: 0.99999 },
  { service: "Cosmos DB for Table - Multi-Region Write", sla: 0.99999 },
  { service: "Cosmos DB for Table - Single Region", sla: 0.9999 },
  { service: "Cosmos DB for Table - Zone Redundant", sla: 0.99995 },
  { service: "Data Lake Analytics", sla: 0.999 },
  { service: "Defender External Attack Surface Management", sla: 0.999 },
  { service: "Duet Enterprise Online", sla: 0.999 },
  { service: "Dynamics 365 Business Central", sla: 0.999 },
  { service: "Dynamics 365 Commerce", sla: 0.999 },
  { service: "Dynamics 365 Customer Insights", sla: 0.999 },
  { service: "Dynamics 365 Customer Service Enterprise", sla: 0.999 },
  { service: "Dynamics 365 Customer Service Insights", sla: 0.999 },
  { service: "Dynamics 365 Customer Service Professional", sla: 0.999 },
  { service: "Dynamics 365 Field Service", sla: 0.999 },
  { service: "Dynamics 365 Finance", sla: 0.999 },
  { service: "Dynamics 365 Fraud Protection", sla: 0.999 },
  { service: "Dynamics 365 Guides", sla: 0.999 },
  { service: "Dynamics 365 Human Resources", sla: 0.999 },
  { service: "Dynamics 365 Intelligent Order Management", sla: 0.999 },
  { service: "Dynamics 365 Marketing", sla: 0.999 },
  { service: "Dynamics 365 Project Operations", sla: 0.999 },
  { service: "Dynamics 365 Remote Assist", sla: 0.999 },
  { service: "Dynamics 365 Sales Enterprise", sla: 0.999 },
  { service: "Dynamics 365 Sales Professional", sla: 0.999 },
  { service: "Dynamics 365 Supply Chain Management", sla: 0.999 },
  { service: "Event Grid", sla: 0.9999 },
  { service: "Event Hubs - Basic Tier", sla: 0.9995 },
  { service: "Event Hubs - Dedicated Tier", sla: 0.9999 },
  { service: "Event Hubs - Premium Tier", sla: 0.9999 },
  { service: "Event Hubs - Standard Tier", sla: 0.9995 },
  { service: "Exchange Online", sla: 0.999 },
  { service: "Exchange Online Archiving", sla: 0.999 },
  { service: "Exchange Online Protection", sla: 0.999 },
  { service: "HDInsight", sla: 0.999 },
  { service: "Health Bot", sla: 0.999 },
  { service: "Log Analytics - Query", sla: 0.999 },
  { service: "Logic Apps", sla: 0.999 },
  { service: "Media Services", sla: 0.999 },
  { service: "MedTech Service", sla: 0.999 },
  { service: "Microsofdt Teams Phone", sla: 0.99999 },
  { service: "Microsoft 365 Apps for Business", sla: 0.999 },
  { service: "Microsoft 365 Apps for Enterprise", sla: 0.999 },
  { service: "Microsoft Cloud App Security", sla: 0.999 },
  { service: "Microsoft Copilot Studio", sla: 0.999 },
  { service: "Microsoft Cost Management", sla: 0.999 },
  { service: "Microsoft Defender for Endpoint", sla: 0.999 },
  { service: "Microsoft Defender for Identity", sla: 0.999 },
  { service: "Microsoft Defender for IoT", sla: 0.999 },
  { service: "Microsoft Entra Domain Services", sla: 0.999 },
  { service: "Microsoft Entra ID Basic", sla: 0.9999 },
  { service: "Microsoft Entra ID Premium", sla: 0.9999 },
  { service: "Microsoft Fabric", sla: 0.999 },
  { service: "Microsoft Genomics", sla: 0.999 },
  { service: "Microsoft Intune", sla: 0.999 },
  { service: "Microsoft MyAnalytics", sla: 0.999 },
  { service: "Microsoft Power Apps", sla: 0.999 },
  { service: "Microsoft Power Automate", sla: 0.999 },
  { service: "Microsoft Power Pages", sla: 0.999 },
  { service: "Microsoft Purview", sla: 0.999 },
  { service: "Microsoft Sentinel", sla: 0.999 },
  { service: "Microsoft Stream (Classic)", sla: 0.999 },
  { service: "Microsoft Sustainability Manager", sla: 0.995 },
  { service: "Microsoft Teams", sla: 0.999 },
  { service: "Microsoft Teams Audio Conferencing", sla: 0.99999 },
  { service: "Microsoft Teams Calling Plans", sla: 0.99999 },
  { service: "Microsoft Teams Voice Quality", sla: 0.999 },
  { service: "Mobile Services - Premium Tier", sla: 0.999 },
  { service: "Mobile Services - Standard Tier", sla: 0.999 },
  { service: "Multi-factor Authentication", sla: 0.999 },
  { service: "Network Watcher", sla: 0.999 },
  { service: "Notification Hubs", sla: 0.999 },
  { service: "Office 365 Advanced Compliance", sla: 0.999 },
  { service: "Office 365 Video", sla: 0.999 },
  { service: "Office Online", sla: 0.999 },
  { service: "On-demand Capacity Reservation for Virtual Machines", sla: 0.999 },
  { service: "OneDrive for Business", sla: 0.999 },
  { service: "Power BI Embedded", sla: 0.999 },
  { service: "Power BI Premium", sla: 0.999 },
  { service: "Power BI Pro", sla: 0.999 },
  { service: "Project", sla: 0.999 },
  { service: "Remote Rendering", sla: 0.999 },
  { service: "SAP HANA on Azure Large Instances - High Availability Pair", sla: 0.9999 },
  { service: "SAP HANA on Azure Single Instance", sla: 0.999 },
  { service: "Scheduler", sla: 0.999 },
  { service: "Service Bus - Single Region / Non Zonal", sla: 0.999 },
  { service: "Service Bus - Zone Redundant", sla: 0.9999 },
  { service: "Service Bus Relay", sla: 0.999 },
  { service: "SharePoint Online", sla: 0.999 },
  { service: "SQL Server Stretch Database", sla: 0.999 },
  { service: "Static Web Apps", sla: 0.9995 },
  { service: "Storage - GRS/GZRS (Cool Blobs)", sla: 0.99 },
  { service: "Storage - GRS/GZRS (Hot Blobs)", sla: 0.999 },
  { service: "Storage - LRS (Cool Blobs)", sla: 0.99 },
  { service: "Storage - LRS (Hot Blobs)", sla: 0.999 },
  { service: "Storage - RAGRS/RAGZRS (Read Cool Blobs)", sla: 0.999 },
  { service: "Storage - RAGRS/RAGZRS (Read Hot Blobs)", sla: 0.9999 },
  { service: "Storage - RAGRS/RAGZRS (Write Cool Blobs)", sla: 0.99 },
  { service: "Storage - RAGRS/RAGZRS (Write Hot Blobs)", sla: 0.999 },
  { service: "Storage - ZRS (Cool Blobs)", sla: 0.99 },
  { service: "Storage - ZRS (Hot Blobs)", sla: 0.999 },
  { service: "Traffic Manager", sla: 0.9999 },
  { service: "Translator API", sla: 0.999 },
  { service: "Universal Print", sla: 0.999 },
  { service: "Virtual Network Gateway (Basic)", sla: 0.999 },
  { service: "Virtual Network Gateway (Not Basic)", sla: 0.9995 },
  { service: "VM - Single Instance", sla: 0.999 },
  { service: "VMs - Availability Set", sla: 0.9995 },
  { service: "VMs - Dedicated Host Group", sla: 0.9995 },
  { service: "VMs - using same Shared Disks", sla: 0.999 },
  { service: "VMSS - Regional", sla: 0.999 },
  { service: "VMSS - Zonal", sla: 0.999 },
  { service: "VMSS - Zone Redundant", sla: 0.9999 },
  { service: "Windows 10 IoT Core Services", sla: 0.999 },
  { service: "Windows 365", sla: 0.999 },
  { service: "Workplace Analytics", sla: 0.999 },
  { service: "Yammer Enterprise", sla: 0.999 }
];

// GET /api/sla
app.get('/api/sla', (req, res) => {
  res.json(SLA_DATA);
});

// POST /api/composite-sla
app.post('/api/composite-sla', (req, res) => {
  const { services } = req.body;
  if (!Array.isArray(services)) {
    return res.status(400).json({ error: "services must be an array" });
  }

  let composite = 1.0;
  for (const serviceName of services) {
    const service = SLA_DATA.find(s => s.service === serviceName);
    if (!service) {
      return res.status(400).json({ error: `Unknown service: ${serviceName}` });
    }
    composite *= service.sla;
  }
  res.json({ composite_sla: Number(composite.toFixed(10)) });
});

const port = process.env.PORT || 8000;
app.listen(port, () => {
  console.log(`Backend listening on port ${port}`);
});