name: Deploy React App to Azure

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci # Use `npm ci` for a clean install
        working-directory: ./frontend # Ensure the working directory is set to the root of your project

      # Step 5: Build the app
      - name: Build the app
        run: npx vite build
        working-directory: ./frontend

      # Debugging step
      - name: Debug env
        run: |
          echo "CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}"
          echo "TENANT_ID=${{ secrets.AZURE_TENANT_ID }}"
          echo "SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          echo "CLIENT_SECRET is set: ${{ secrets.AZURE_CLIENT_SECRET != '' }}"

      # Step 6: Deploy to Azure App Service
      - name: Azure Login
        uses: azure/login@v1.4.3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          auth-type: SERVICE_PRINCIPAL
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: catewebapp1   
          package: ./frontend/dist 