name: Deploy React App to Azure

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Use Node.js 18 LTS for compatibility with Vite

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci # Use `npm ci` for a clean install

    # Step 4: Debug permissions (moved earlier)
    - name: Debug permissions
      run: ls -la node_modules/.bin

    # Step 5: Fix permissions for all binaries
    - name: Fix permissions for binaries
      run: chmod +x node_modules/.bin/*

    # Step 6: Verify Vite binary
    - name: Verify Vite binary
      run: node_modules/.bin/vite --version

    # Step 7: Build the app
    - name: Build the app
      run: node node_modules/.bin/vite build # Directly run the Vite binary

    # Step 8: Deploy to Azure App Service
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: cate # Replace with your Azure App Service name
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./dist