name: Deploy React App to Azure

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22' # Match the Node.js version in Azure App Service

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Debug permissions
    - name: Debug permissions
      run: ls -la node_modules/.bin

    # Fix permissions for vite binary
    - name: Fix permissions for vite
      run: chmod +x node_modules/.bin/vite

    # Step 4: Build the app
    - name: Build the app
      run: npx vite build

    # Step 5: Deploy to Azure App Service
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: cate # Replace with your Azure App Service name
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./dist